// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL_JBRgpLdXX_vcCN37GvF1of9r_m7N-A',
    appId: '1:256646525651:web:fb7ca1608c4aa36a655a26',
    messagingSenderId: '256646525651',
    projectId: 'boom-boom-37b31',
    authDomain: 'boom-boom-37b31.firebaseapp.com',
    storageBucket: 'boom-boom-37b31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvrV4ItEJ4cfxxIQ0Xzf4niqfehwwrIOs',
    appId: '1:256646525651:android:2a1ecc227713d538655a26',
    messagingSenderId: '256646525651',
    projectId: 'boom-boom-37b31',
    storageBucket: 'boom-boom-37b31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCE2uZhg8NSN-LVhihFiMBIW2Mv7PxCbU',
    appId: '1:256646525651:ios:90b17dc4a5d16deb655a26',
    messagingSenderId: '256646525651',
    projectId: 'boom-boom-37b31',
    storageBucket: 'boom-boom-37b31.appspot.com',
    iosClientId: '256646525651-m0bv3sibb3lbhppq8m3m7lr7cbefeoo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomBoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCE2uZhg8NSN-LVhihFiMBIW2Mv7PxCbU',
    appId: '1:256646525651:ios:90b17dc4a5d16deb655a26',
    messagingSenderId: '256646525651',
    projectId: 'boom-boom-37b31',
    storageBucket: 'boom-boom-37b31.appspot.com',
    iosClientId: '256646525651-m0bv3sibb3lbhppq8m3m7lr7cbefeoo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomBoom',
  );
}
